hydra:
  run:
    dir: "data/${now:%Y-%m-%d_%H-%M-%S}"
  sweep:
    dir: "data/${now:%Y-%m-%d_%H-%M-%S}"
    subdir: ${hydra.job.num}

checkpoint:
  monitor: "val_acc"
  mode: "max"
  dirpath: "ckpts"
  filename: "{epoch:03d}-{val_acc:.3f}"
  save_last: True
  verbose: True
  save_top_k: 1
