hydra:
  run:
    dir: "data/${now:%Y-%m-%d_%H-%M-%S}"
  sweep:
    dir: "data/${now:%Y-%m-%d_%H-%M-%S}"
    subdir: ${hydra.job.num}

checkpoint:
  monitor: "x"
  mode: "max"
  verbose: True
  save_top_k: 1
